name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: ThaddeusTeh2
          token: ${{ secrets.METRICS_TOKEN }}

          base: header, activity, community, repositories, metadata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_indepth: yes

          plugin_lines: yes
          plugin_licenses: yes

          plugin_habits: yes
          plugin_habits_days: 14

          plugin_activity: yes
          plugin_repositories: yes
          plugin_followup: yes

          plugin_people: yes
          plugin_people_limit: 24
